<a href="https://colab.research.google.com/github/ramuked/Energy-Ouput-CCPP/blob/main/Electrical_Energy_output_of_a_Combined_Cycle_Power_Plant.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Electrical Energy output of a Combined Cycle Power Plant
###Made while learning ANNs with Tensorflow

##importing required libraries

In [52]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf
import seaborn as sns

##Data Preprocessing

###importing the dataset

In [53]:
dataset = pd.read_excel("Folds5x2_pp.xlsx")

In [54]:
print(dataset.head())

      AT      V       AP     RH      PE
0  14.96  41.76  1024.07  73.17  463.26
1  25.18  62.96  1020.04  59.08  444.37
2   5.11  39.40  1012.16  92.14  488.56
3  20.86  57.32  1010.24  76.64  446.48
4  10.82  37.50  1009.23  96.62  473.90


In [55]:
print(dataset.shape)

(9568, 5)


In [56]:
print(dataset.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9568 entries, 0 to 9567
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   AT      9568 non-null   float64
 1   V       9568 non-null   float64
 2   AP      9568 non-null   float64
 3   RH      9568 non-null   float64
 4   PE      9568 non-null   float64
dtypes: float64(5)
memory usage: 373.9 KB
None


In [57]:
print(dataset.describe())

                AT            V           AP           RH           PE
count  9568.000000  9568.000000  9568.000000  9568.000000  9568.000000
mean     19.651231    54.305804  1013.259078    73.308978   454.365009
std       7.452473    12.707893     5.938784    14.600269    17.066995
min       1.810000    25.360000   992.890000    25.560000   420.260000
25%      13.510000    41.740000  1009.100000    63.327500   439.750000
50%      20.345000    52.080000  1012.940000    74.975000   451.550000
75%      25.720000    66.540000  1017.260000    84.830000   468.430000
max      37.110000    81.560000  1033.300000   100.160000   495.760000


In [58]:
X = dataset.iloc[:,0:-1].values
Y = dataset.iloc[:,-1].values

In [59]:
print(X)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]


In [60]:
print(Y)

[463.26 444.37 488.56 ... 429.57 435.74 453.28]


###splitting the data into test and training set

In [61]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,random_state=0)

In [62]:
print(X_train)
print(Y_train)

[[  11.22   43.13 1017.24   80.9 ]
 [  13.67   54.3  1015.92   75.42]
 [  32.84   77.95 1014.68   45.8 ]
 ...
 [  16.81   38.52 1018.26   75.21]
 [  12.8    41.16 1022.43   86.19]
 [  32.32   67.9  1006.08   37.93]]
[473.93 467.87 431.97 ... 459.01 462.72 428.12]


##Building The ANN

###Initializing the ANN

In [63]:
ann = tf.keras.models.Sequential()

###Adding the input layer and the first hidden layer

In [64]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

###Adding the second layer

In [65]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

###Adding the output layer

In [66]:
ann.add(tf.keras.layers.Dense(units=1))

##Training the ANN

###Compiling the ANN

In [67]:
ann.compile(optimizer = 'adam',loss='mean_squared_error')

###Training the ANN Model on the training Set

In [68]:
ann.fit(X_train,Y_train, batch_size = 32,epochs = 100)

Epoch 1/100
240/240 [==============================] - 1s 1ms/step - loss: 5141.0508
Epoch 2/100
240/240 [==============================] - 0s 1ms/step - loss: 245.5231
Epoch 3/100
240/240 [==============================] - 0s 1ms/step - loss: 231.1456
Epoch 4/100
240/240 [==============================] - 0s 1ms/step - loss: 213.0437
Epoch 5/100
240/240 [==============================] - 0s 1ms/step - loss: 193.0678
Epoch 6/100
240/240 [==============================] - 0s 1ms/step - loss: 172.3363
Epoch 7/100
240/240 [==============================] - 0s 1ms/step - loss: 151.3625
Epoch 8/100
240/240 [==============================] - 0s 1ms/step - loss: 130.6096
Epoch 9/100
240/240 [==============================] - 0s 1ms/step - loss: 111.6797
Epoch 10/100
240/240 [==============================] - 0s 1ms/step - loss: 94.6015
Epoch 11/100
240/240 [==============================] - 0s 1ms/step - loss: 80.3256
Epoch 12/100
240/240 [==============================] - 0s 1ms/step - loss:

###Predicting the results of the Test Set

In [77]:
y_pred = ann.predict(X_test)
np.set_printoptions(precision=2)

print(np.concatenate((y_pred.reshape(len(y_pred),1) , Y_test.reshape(len(Y_test),1)),1))



[[430.85 431.23]
 [461.78 460.01]
 [465.26 461.14]
 ...
 [472.49 473.26]
 [439.35 438.  ]
 [458.5  463.28]]
